// GENERATED by build_data/make_dart_districts.py — do not edit by hand.
// Source: LGD district boundaries via DataMeet (CC0 1.0), Dec 2023 vintage,
// simplified; each state's districts are projected into that state's own 0..1000 space.
// Credit in-app: "District boundaries: Local Government Directory via DataMeet (CC0)".
// District data lives in india_districts_p1..p4.dart (split for transport).
// ignore_for_file: prefer_single_quotes

import 'district_shape.dart';
import 'india_districts_p1.dart';
import 'india_districts_p2.dart';
import 'india_districts_p3.dart';
import 'india_districts_p4.dart';

export 'district_shape.dart';

const List<DistrictShape> indiaDistricts = [
  ...districtsP1,
  ...districtsP2,
  ...districtsP3,
  ...districtsP4,
];
